const de = {
  search: "Ideen durchsuchen …", searchHint: "Titel und Inhalt · Strg+K", noResults: "Keine passenden Ideen.", allProgress: "Jeder Fortschritt", allStatus: "Jede Priorität", allCategories: "Alle Kategorien",
  editor: "Bearbeiten", reader: "Gesamtdokument", trash: "Papierkorb", activity: "Aktionen", backup: "Backup herunterladen", importBackup: "Backup öffnen", backupHint: "Enthält Texte, Anhänge, Skizzen und Versionsverlauf. Eine Sicherung wird als neues Projekt geöffnet.",
  undo: "Rückgängig", undone: "Rückgängig gemacht", restore: "Wiederherstellen", emptyTrash: "Der Papierkorb ist leer.", trashHint: "Gelöschte Ideen bleiben mit ihren Unterideen, Anhängen und Skizzen erhalten.", emptyActivity: "Noch keine aufgezeichneten Aktionen.", activityHint: "Aktionen lassen sich zurücknehmen, solange die betroffenen Inhalte seitdem unverändert sind. Textversionen findest du zusätzlich im Verlauf der jeweiligen Idee.",
  deleteConfirm: "„{title}“ mit allen Unterideen in den Papierkorb verschieben?", count: "{n} Ideen", savedAction: "Aktion gespeichert", rename: "Umbenennen", archive: "Archivieren", unarchive: "Aus Archiv holen", archived: "Archiv", active: "Aktive Projekte", duplicate: "Duplizieren", copyTitle: "{title} (Kopie)", projectTitle: "Projektname", cancel: "Abbrechen", save: "Speichern", close: "Schließen",
  exportHtml: "HTML mit Bildern", exportMd: "Markdown", exportJson: "JSON", print: "Drucken / PDF", contents: "Inhalt", exportBusy: "Dokument wird vorbereitet …", openIdea: "Idee öffnen", noDocument: "Das Projekt hat noch keine Ideen.",
  links: "Verknüpfungen", backlinks: "Hier erwähnt", noBacklinks: "Noch keine Verweise auf diese Idee.", linkHint: "[[ eingeben, um eine Idee zu verknüpfen.", missingLink: "Verknüpfte Idee fehlt", insertLink: "Verknüpfung einfügen", breadcrumb: "Position im Projekt", moveUp: "Nach oben", moveDown: "Nach unten", move: "Verschieben", parent: "Übergeordnete Idee", root: "Kategorie-Ebene", category: "Kategorie", collapse: "Unterideen ein-/ausklappen",
  addTemplate: "Idee aus Vorlage", template: "Vorlage", blank: "Leere Idee", mechanic: "Mechanik", enemy: "Gegner", playtest: "Playtest", example: "Beispielprojekt öffnen", exampleTitle: "Waldläufer – Designbeispiel", create: "Erstellen",
  chooseFiles: "Dateien auswählen", removeAttachment: "Anhang entfernen", removeConfirm: "Diesen Anhang von der Idee entfernen?", preview: "Änderungsvorschau", before: "Vorher", after: "Nachher", apply: "Änderungen übernehmen", discard: "Verwerfen", applied: "Änderungen übernommen", overview: "Projektüberblick (Auszüge)", context: "Kontext: {included} von {total} Ideen; längere Texte ggf. gekürzt.", chatHint: "Dieses Gespräch gehört zu diesem Projekt. Änderungen werden erst nach deiner Prüfung übernommen.", clearChat: "Dieses Projektgespräch löschen?", retry: "Erneut versuchen", draft: "Ein ungespeicherter lokaler Entwurf ist vorhanden.", recoverDraft: "Entwurf laden", discardDraft: "Entwurf verwerfen", shortcuts: "Strg+K: Suche · Strg+S: Speichern · Esc: Vollbild verlassen",
  kinds: { create: "Idee erstellt", trash: "In Papierkorb verschoben", restore: "Wiederhergestellt", duplicate: "Dupliziert", move: "Verschoben", copilot: "Copilot-Änderungen", project: "Projekt geändert", revision: "Textversion wiederhergestellt", categories: "Kategorien geändert", attachment: "Anhang entfernt" },
  fields: { title: "Titel", body: "Inhalt", pillar: "Kategorie", parent: "Übergeordnete Idee", order: "Reihenfolge", status: "Priorität", progress: "Fortschritt", kind: "Typ", attachments: "Anhänge", canvas: "Skizze" },
  errors: { CHANGED_SINCE_ACTION: "Inhalte wurden inzwischen geändert. Rückgängig würde neuere Arbeit überschreiben. Nutze den Verlauf der Idee.", STALE_PROPOSAL: "Die betroffenen Ideen wurden inzwischen geändert. Bitte lass einen neuen Vorschlag erstellen.", RESTORE_CONFLICT: "Diese Ideen existieren bereits. Es wurde nichts überschrieben.", INVALID_BACKUP: "Diese Datei ist kein gültiges GameSketch-Backup.", ALREADY_UNDONE: "Diese Aktion wurde bereits rückgängig gemacht.", PROPOSAL_NOT_FOUND: "Der Vorschlag ist nicht mehr vorhanden. Bitte erstelle einen neuen.", PROPOSAL_OWNER: "Der Vorschlag gehört zu einem anderen Benutzer.", PROJECT_NOT_FOUND: "Dieses Projekt wurde nicht gefunden." },
};
const en = {
  search: "Search ideas …", searchHint: "Titles and content · Ctrl+K", noResults: "No matching ideas.", allProgress: "Any progress", allStatus: "Any priority", allCategories: "All categories",
  editor: "Edit", reader: "Full document", trash: "Trash", activity: "Actions", backup: "Download backup", importBackup: "Open backup", backupHint: "Includes text, attachments, drawings and version history. A backup opens as a new project.",
  undo: "Undo", undone: "Undone", restore: "Restore", emptyTrash: "Trash is empty.", trashHint: "Deleted ideas keep their children, attachments and drawings.", emptyActivity: "No recorded actions yet.", activityHint: "Undo is available while affected content has no newer changes. Each idea also has its own text history.",
  deleteConfirm: "Move “{title}” and all its children to trash?", count: "{n} ideas", savedAction: "Action saved", rename: "Rename", archive: "Archive", unarchive: "Unarchive", archived: "Archive", active: "Active projects", duplicate: "Duplicate", copyTitle: "{title} (copy)", projectTitle: "Project name", cancel: "Cancel", save: "Save", close: "Close",
  exportHtml: "HTML with images", exportMd: "Markdown", exportJson: "JSON", print: "Print / PDF", contents: "Contents", exportBusy: "Preparing document …", openIdea: "Open idea", noDocument: "This project has no ideas yet.",
  links: "Links", backlinks: "Mentioned in", noBacklinks: "No other ideas link here yet.", linkHint: "Type [[ to link an idea.", missingLink: "Linked idea is missing", insertLink: "Insert link", breadcrumb: "Position in project", moveUp: "Move up", moveDown: "Move down", move: "Move", parent: "Parent idea", root: "Category level", category: "Category", collapse: "Toggle children",
  addTemplate: "Idea from template", template: "Template", blank: "Blank idea", mechanic: "Mechanic", enemy: "Enemy", playtest: "Playtest", example: "Open example project", exampleTitle: "Forest Runner – design example", create: "Create",
  chooseFiles: "Choose files", removeAttachment: "Remove attachment", removeConfirm: "Remove this attachment from the idea?", preview: "Review changes", before: "Before", after: "After", apply: "Apply changes", discard: "Discard", applied: "Changes applied", overview: "Project overview (excerpts)", context: "Context: {included} of {total} ideas; longer text may be shortened.", chatHint: "This conversation belongs to this project. Changes are applied after your review.", clearChat: "Delete this project conversation?", retry: "Retry", draft: "An unsaved local draft is available.", recoverDraft: "Load draft", discardDraft: "Discard draft", shortcuts: "Ctrl+K: Search · Ctrl+S: Save · Esc: Leave fullscreen",
  kinds: { create: "Idea created", trash: "Moved to trash", restore: "Restored", duplicate: "Duplicated", move: "Moved", copilot: "Copilot changes", project: "Project changed", revision: "Text version restored", categories: "Categories changed", attachment: "Attachment removed" },
  fields: { title: "Title", body: "Content", pillar: "Category", parent: "Parent idea", order: "Order", status: "Priority", progress: "Progress", kind: "Type", attachments: "Attachments", canvas: "Drawing" },
  errors: { CHANGED_SINCE_ACTION: "Content has newer changes. Undo would overwrite them. Use the idea’s history instead.", STALE_PROPOSAL: "Affected ideas have changed. Please request a fresh proposal.", RESTORE_CONFLICT: "These ideas already exist. Nothing was overwritten.", INVALID_BACKUP: "This is not a valid GameSketch backup.", ALREADY_UNDONE: "This action was already undone.", PROPOSAL_NOT_FOUND: "This proposal is no longer available. Please request a new one.", PROPOSAL_OWNER: "This proposal belongs to another user.", PROJECT_NOT_FOUND: "Project not found." },
};
const ru = {
  search: "Поиск идей …", searchHint: "Заголовки и текст · Ctrl+K", noResults: "Ничего не найдено.", allProgress: "Любой прогресс", allStatus: "Любой приоритет", allCategories: "Все категории",
  editor: "Редактор", reader: "Весь документ", trash: "Корзина", activity: "Действия", backup: "Скачать резервную копию", importBackup: "Открыть резервную копию", backupHint: "Тексты, вложения, рисунки и история версий. Копия открывается как новый проект.", undo: "Отменить", undone: "Отменено", restore: "Восстановить", emptyTrash: "Корзина пуста.", trashHint: "Удалённые идеи сохраняют дочерние идеи, вложения и рисунки.", emptyActivity: "Действий пока нет.", activityHint: "Отмена доступна, пока затронутые данные не изменены. История текста находится в каждой идее.",
  deleteConfirm: "Переместить «{title}» и все дочерние идеи в корзину?", count: "Идей: {n}", savedAction: "Действие сохранено", rename: "Переименовать", archive: "Архивировать", unarchive: "Извлечь из архива", archived: "Архив", active: "Активные проекты", duplicate: "Дублировать", copyTitle: "{title} (копия)", projectTitle: "Название проекта", cancel: "Отмена", save: "Сохранить", close: "Закрыть",
  exportHtml: "HTML с изображениями", exportMd: "Markdown", exportJson: "JSON", print: "Печать / PDF", contents: "Содержание", exportBusy: "Подготовка документа …", openIdea: "Открыть идею", noDocument: "В проекте пока нет идей.", links: "Ссылки", backlinks: "Упоминается в", noBacklinks: "Ссылок на эту идею пока нет.", linkHint: "Введите [[ для ссылки на идею.", missingLink: "Связанная идея отсутствует", insertLink: "Вставить ссылку", breadcrumb: "Положение в проекте", moveUp: "Вверх", moveDown: "Вниз", move: "Переместить", parent: "Родительская идея", root: "Уровень категории", category: "Категория", collapse: "Показать/скрыть дочерние идеи",
  addTemplate: "Идея из шаблона", template: "Шаблон", blank: "Пустая идея", mechanic: "Механика", enemy: "Противник", playtest: "Плейтест", example: "Открыть пример проекта", exampleTitle: "Лесной бегун — пример дизайна", create: "Создать", chooseFiles: "Выбрать файлы", removeAttachment: "Удалить вложение", removeConfirm: "Убрать вложение из идеи?", preview: "Просмотр изменений", before: "До", after: "После", apply: "Применить изменения", discard: "Отклонить", applied: "Изменения применены", overview: "Обзор проекта (выдержки)", context: "Контекст: {included} из {total} идей; длинные тексты могут быть сокращены.", chatHint: "Разговор относится к этому проекту. Изменения применяются после вашей проверки.", clearChat: "Удалить разговор этого проекта?", retry: "Повторить", draft: "Есть несохранённый локальный черновик.", recoverDraft: "Загрузить черновик", discardDraft: "Удалить черновик", shortcuts: "Ctrl+K: Поиск · Ctrl+S: Сохранить · Esc: Выйти из полного экрана",
  kinds: { create: "Идея создана", trash: "Перемещено в корзину", restore: "Восстановлено", duplicate: "Дублировано", move: "Перемещено", copilot: "Изменения Copilot", project: "Проект изменён", revision: "Версия текста восстановлена", categories: "Категории изменены", attachment: "Вложение удалено" },
  fields: { title: "Заголовок", body: "Содержание", pillar: "Категория", parent: "Родительская идея", order: "Порядок", status: "Приоритет", progress: "Прогресс", kind: "Тип", attachments: "Вложения", canvas: "Рисунок" },
  errors: { CHANGED_SINCE_ACTION: "Есть более новые изменения. Используйте историю идеи.", STALE_PROPOSAL: "Идеи изменились. Запросите новое предложение.", RESTORE_CONFLICT: "Эти идеи уже существуют. Данные не перезаписаны.", INVALID_BACKUP: "Это не резервная копия GameSketch.", ALREADY_UNDONE: "Действие уже отменено.", PROPOSAL_NOT_FOUND: "Предложение недоступно. Запросите новое.", PROPOSAL_OWNER: "Предложение принадлежит другому пользователю.", PROJECT_NOT_FOUND: "Проект не найден." },
};
de.errors.BACKUP_TOO_LARGE = "Dieses Projekt überschreitet das Dateilimit für Backups (100 MiB komprimiert / 200 MiB entpackt). Sichere den Projektordner bei beendetem Server direkt.";
en.errors.BACKUP_TOO_LARGE = "This project exceeds the backup limit (100 MiB compressed / 200 MiB unpacked). Copy the project folder with the server stopped.";
ru.errors.BACKUP_TOO_LARGE = "Проект превышает лимит копии (100 МиБ сжато / 200 МиБ распаковано). Скопируйте папку проекта при остановленном сервере.";
export default { de, en, ru };
