const templates = {
  de: {
    mechanic: { title: "Ausweichrolle", body: "## Zweck\nDie Rolle erlaubt riskantes Ausweichen und schafft ein kurzes Angriffsfenster.\n\n## Regeln\n- Eingabe: Leertaste + Bewegungsrichtung.\n- Dauer: 0,35 s; davon 0,15 s unverwundbar.\n- Kosten: 25 Ausdauer von maximal 100.\n- Ohne Richtung: rückwärts ausweichen.\n\n## Feedback\nStaubspur, kurzer Klang und sichtbarer Ausdauerverbrauch. Treffer während der Erholung bleiben möglich.\n\n## Sonderfälle\nAn Wänden endet die Bewegung; im Menü und während eines Stuns ist die Rolle gesperrt.\n\n## Abnahme\n- [ ] Eingabe fühlt sich bei 30 und 60 FPS gleich an.\n- [ ] Kein Durchrollen durch Wände.\n- [ ] Drei aufeinanderfolgende Rollen lassen noch eine kleine Reserve.\n\n## Offene Frage\nIst das Ausweichfenster für neue Spieler gut lesbar? Im Playtest prüfen." },
    enemy: { title: "Waldwächter", body: "## Rolle im Spiel\nEin langsamer Nahkämpfer, der das Erkennen angekündigter Angriffe lehrt.\n\n## Verhalten\nPatrouille → Spieler in 8 m entdecken → annähern → Hieb vorbereiten → angreifen → 1 s erholen.\n\n## Ausgangswerte\n| Wert | Startwert |\n| --- | --- |\n| Lebenspunkte | 60 |\n| Schaden | 20 |\n| Ankündigung | 0,8 s |\n| Reichweite | 2 m |\n\n## Lesbarkeit\nVor dem Hieb hebt der Wächter den Arm; der Gefahrenbereich glüht kurz auf.\n\n## Belohnung\n5 Holz und eine sichere Pause nach dem Kampf.\n\n## Testfälle\n- [ ] Angriff bricht bei verlorener Sicht nicht mitten in der Animation ab.\n- [ ] Spieler kann während der Erholung angreifen.\n- [ ] Wächter blockiert keinen notwendigen Ausgang." },
    playtest: { title: "Playtest: erster Kampf", kind: "note", body: "## Hypothese\nNeue Spieler verstehen den angekündigten Hieb und nutzen die Ausweichrolle innerhalb von drei Versuchen.\n\n## Aufbau\n5 Personen, je 10 Minuten; erster Raum mit einem Waldwächter. Keine mündliche Erklärung der Mechanik.\n\n## Aufgaben\n1. Besiege den Wächter.\n2. Erreiche den Ausgang.\n3. Beschreibe, wann du sicher angreifen konntest.\n\n## Beobachtung\n| Person | Versuche | Rolle erkannt? | Auffälligkeit |\n| --- | --- | --- | --- |\n| P1 | — | — | — |\n\n## Erfolgskriterium\nMindestens 4 von 5 Personen erkennen das Angriffsfenster ohne Hinweis.\n\n## Ergebnis\nNoch nicht durchgeführt.\n\n## Nächste Entscheidung\nBei weniger als 4 Erfolgen zuerst die Angriffsankündigung verbessern und erneut testen." },
  },
  en: {
    mechanic: { title: "Dodge roll", body: "## Purpose\nReward well-timed dodges with a short attack window.\n\n## Rules\n- Input: Space + movement direction.\n- Duration: 0.35 s; invulnerable for 0.15 s.\n- Cost: 25 stamina out of 100.\n- No direction: roll backwards.\n\n## Feedback\nDust trail, short sound, visible stamina use. Recovery remains vulnerable.\n\n## Edge cases\nWalls stop movement. Rolling is disabled in menus and during stun.\n\n## Acceptance\n- [ ] Same feel at 30 and 60 FPS.\n- [ ] Cannot pass through walls.\n- [ ] Three rolls leave a small reserve.\n\n## Open question\nCan new players read the dodge window? Check in a playtest." },
    enemy: { title: "Forest guardian", body: "## Role\nA slow melee enemy that teaches players to read attack cues.\n\n## Behaviour\nPatrol → detect player within 8 m → approach → wind up → strike → recover for 1 s.\n\n## Initial values\n| Value | Start |\n| --- | --- |\n| Health | 60 |\n| Damage | 20 |\n| Wind-up | 0.8 s |\n| Range | 2 m |\n\n## Readability\nRaises its arm and briefly lights the danger area before striking.\n\n## Reward\n5 wood and a safe pause after combat.\n\n## Tests\n- [ ] Losing sight does not interrupt a strike mid-animation.\n- [ ] Player can attack during recovery.\n- [ ] Guardian cannot block a required exit." },
    playtest: { title: "Playtest: first fight", kind: "note", body: "## Hypothesis\nNew players read the wind-up and use the dodge roll within three attempts.\n\n## Setup\n5 people, 10 minutes each. First room with one forest guardian. No verbal explanation of the mechanic.\n\n## Tasks\n1. Defeat the guardian.\n2. Reach the exit.\n3. Describe when it was safe to attack.\n\n## Observations\n| Person | Attempts | Found roll? | Notes |\n| --- | --- | --- | --- |\n| P1 | — | — | — |\n\n## Success criterion\nAt least 4 of 5 people identify the attack window without hints.\n\n## Result\nNot run yet.\n\n## Next decision\nIf fewer than 4 succeed, improve the attack cue first and retest." },
  },
  ru: {
    mechanic: { title: "Уклонение кувырком", body: "## Цель\nВознаградить своевременное уклонение коротким окном для атаки.\n\n## Правила\n- Пробел + направление движения.\n- Длительность 0,35 с, неуязвимость 0,15 с.\n- Стоимость: 25 выносливости из 100.\n- Без направления: кувырок назад.\n\n## Обратная связь\nСлед пыли, короткий звук, расход выносливости. Во время восстановления игрок уязвим.\n\n## Особые случаи\nСтены останавливают движение. В меню и при оглушении кувырок недоступен.\n\n## Проверка\n- [ ] Одинаковые ощущения при 30 и 60 FPS.\n- [ ] Нельзя проходить сквозь стены.\n- [ ] После трёх кувырков остаётся небольшой запас.\n\n## Вопрос\nПонимают ли новички момент уклонения? Проверить на плейтесте." },
    enemy: { title: "Лесной страж", body: "## Роль\nМедленный противник ближнего боя учит распознавать подготовку атаки.\n\n## Поведение\nПатруль → обнаружить игрока в 8 м → подойти → замах → удар → восстановление 1 с.\n\n## Начальные значения\n| Параметр | Значение |\n| --- | --- |\n| Здоровье | 60 |\n| Урон | 20 |\n| Замах | 0,8 с |\n| Дальность | 2 м |\n\n## Сигналы\nПеред ударом поднимает руку; опасная зона кратко подсвечивается.\n\n## Награда\n5 дерева и безопасная пауза.\n\n## Проверка\n- [ ] Потеря видимости не обрывает анимацию удара.\n- [ ] Во время восстановления можно атаковать.\n- [ ] Страж не перекрывает необходимый выход." },
    playtest: { title: "Плейтест: первый бой", kind: "note", body: "## Гипотеза\nНовички распознают замах и используют кувырок за три попытки.\n\n## Условия\n5 человек, по 10 минут. Первая комната с одним лесным стражем. Без устных объяснений механики.\n\n## Задания\n1. Победить стража.\n2. Дойти до выхода.\n3. Рассказать, когда было безопасно атаковать.\n\n## Наблюдения\n| Участник | Попытки | Нашёл кувырок? | Заметки |\n| --- | --- | --- | --- |\n| P1 | — | — | — |\n\n## Критерий успеха\nМинимум 4 из 5 понимают окно атаки без подсказок.\n\n## Результат\nЕщё не проведён.\n\n## Следующее решение\nЕсли успехов меньше 4, сначала улучшить сигнал атаки и повторить тест." },
  },
};
export function nodeTemplate(key, lang) { return { ...(templates[lang] || templates.en)[key], progress: "needs_work" }; }
